# rates of timers in Hz
rate:
  check_subscribers: 1 # [Hz]
  check_balloons: 20
  state_machine: 30


# should the UAV land after flying through all the waypoints?
land_at_the_end: false

#arena width
arena_width: 30
#arena length
arena_length: 40
arena_accuracy: 300
#arena_center_x
arena_center_x: 15
arena_center_y: 20

#height where drone will operate ( up to this height )
height: 4
#idle_time
idle_time: 1
#circling radius - define width from the balloon to circle around
circling_radius: 3
#circle accuracy - how many points should be in circle trajectory
circle_accuracy: 100
#velocity for goTo's
vel: 1
#distance to the balloon
dist_to_balloon: 3
#trajectory length
traj_len: 40
#traj time
traj_time: 8
#distance error to target the closest balloon so, it will be compared to current chosen via KF + dist_error 
dist_error: 0.5
#time for waiting for KF reset
wait_for_ball: 2


world_frame_id: "local_origin"
world_point:
  x: 0.0
  y: 0.0
  z: 0.0

