# rates of timers in Hz
rate:
  publish_dist_to_waypoint: 1 # [Hz]
  check_subscribers: 1 # [Hz]
  publish_goto: 10 # [Hz]


# should the UAV land after flying through all the waypoints?
land_at_the_end: false

#arena width
arena_width: 10
#arena length
arena_length: 10
#height where drone will operate ( up to this height )
height: 3
#idle_time
idle_time: 1
#circling radius - define width from the balloon to circle around
circling_radius: 3
#circle accuracy - how many points should be in circle trajectory
circle_accuracy: 100
#velocity for goTo's
vel: 1
#distance to the balloon
dist_to_balloon: 3
#trajectory length
traj_len: 40
#traj time
traj_time: 8

